import { Creepster } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar/page";

const creepster = Creepster({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next JS Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${creepster.className}
          min-h-screen
          bg-gradient-to-br from-black via-red-950 to-black
          text-red-100
          antialiased
        `}
      >
        {/* Dark overlay for depth */}
        <div className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(255,0,0,0.15),transparent_60%)]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
