import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next JS Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen ">
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased   min-h-screen bg-gradient-to-r from-red-500 via-orange-500 to-yellow-500`}
      >
        {/* 👇 CONTENT CONTAINER ONLY */}
        <div className="" >
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
